---
format_version: 7
common:
  deploy-tasks: &deploy-tasks
    - exec:
        command: bash
        arguments:
          - -c 
          - echo "Deploy to ${ENV_NAME} environment"
pipelines:
  java_microservice:
    group: microservices
    lock_behavior: unlockWhenFinished
    label_template: "${git_java_microservice}"
    materials:
      git_java_microservice:
        git: "https://github.com/rromanovs/api_tests_ci.git"
        branch: main
        shallow_clone: true
        auto_update: true
    stages:
      - build:
          jobs:
            build:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "Building Java app"
      - deploy-dev:
          environment_variables:
            ENV_NAME: dev
          jobs:
            deploy:
              tasks: *deploy-tasks
      - test-dev:
          jobs:
            test:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "Testing DEV"
      - deploy-int:
          environment_variables:
            ENV_NAME: int
          jobs:
            deploy:
              tasks: *deploy-tasks
      - test-int:
          jobs:
            test:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "Testing INT"
      - deploy-prd:
          environment_variables:
            ENV_NAME: prod
          jobs:
            deploy:
              tasks: *deploy-tasks
      - test-prd:
          jobs:
            test:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "Testing PROD"


