---
format_version: 7
pipelines:
  java_microservice:
    group: microservices
    lock_behavior: unlockWhenFinished
    label_template: "${git_java_microservice}"
    materials:
      git_java_microservice:
        git: "https://github.com/rromanovs/api_tests_ci.git"
        branch: main
        shallow_clone: true
        auto_update: true
    stages:
      - build:
          jobs:
            build:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "Building Java app"
      - deploy-dev:
          jobs:
            deploy:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "Deploy to DEV"
      - test-dev:
          jobs:
            test:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "Testing DEV"
      - deploy-int:
          jobs:
            deploy:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "Deploy to INT"
      - test-int:
          jobs:
            test:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "Testing INT"
      - deploy-prd:
          jobs:
            deploy:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "Deploy to PROD"
      - test-prd:
          jobs:
            test:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "Testing PROD"


